// Generated by `swift run collection-counts` — do not edit by hand.
// Approximate archive.org numFound per featured collection for the default
// English language selection, captured at generation time.
public enum CollectionBundledCounts {
    public static let languages: Set<String> = ["eng"]
    public static let counts: [String: Int] = [
        "great-books": 632,
        "great-books-spa": 33,
        "great-books-deu": 28,
        "great-books-ita": 13,
        "great-books-grc": 30,
        "greater-books": 1623,
        "lv-adventure": 202,
        "lv-ancient-world": 490,
        "lv-biography": 548,
        "lv-drama-plays": 938,
        "lv-essays-ideas": 1926,
        "lv-fantasy-mythology": 795,
        "lv-general-fiction": 6609,
        "lv-history": 1401,
        "lv-horror-gothic": 386,
        "lv-mystery-crime": 1303,
        "lv-philosophy-mind": 223,
        "lv-poetry": 2617,
        "lv-religion": 730,
        "lv-romance": 1095,
        "lv-satire-humor": 803,
        "lv-science-fiction": 473,
        "lv-science-nature": 1724,
        "lv-short-stories": 710,
        "lv-travel": 559,
        "lv-war-military": 958,
        "popular-librivox": 18821
    ]
}