// Generated by `swift run collection-counts` — do not edit by hand.
// Approximate archive.org numFound per featured collection for the default
// English language selection, captured at generation time.
public enum CollectionBundledCounts {
    public static let languages: Set<String> = ["eng"]
    public static let counts: [String: Int] = [
        "great-books": 405,
        "great-books-deu": 28,
        "great-books-grc": 30,
        "great-books-ita": 13,
        "great-books-spa": 33,
        "greater-books": 916,
        "lv-adventure": 202,
        "lv-ancient-world": 399,
        "lv-biography": 549,
        "lv-drama-plays": 939,
        "lv-essays-ideas": 794,
        "lv-fantasy-mythology": 795,
        "lv-general-fiction": 675,
        "lv-history": 1404,
        "lv-horror-gothic": 387,
        "lv-mystery-crime": 1305,
        "lv-philosophy-mind": 223,
        "lv-poetry": 2622,
        "lv-religion": 732,
        "lv-romance": 1098,
        "lv-satire-humor": 805,
        "lv-science-fiction": 474,
        "lv-science-nature": 1458,
        "lv-short-stories": 713,
        "lv-travel": 562,
        "lv-war-military": 393,
        "popular-librivox": 18826
    ]
}