import Foundation
import VoxglassCore

let collections = IACollectionStore.collections(for: [])
let languageClause = LibriVoxLanguage.clause(for: ["eng"])
let outputPath = "Voxglass/Core/Catalog/CollectionBundledCounts.swift"

var counts: [String: Int] = [:]
let semaphore = DispatchSemaphore(value: 0)

for collection in collections {
    let query = collection.archiveQuery + languageClause
    var components = URLComponents(string: "https://archive.org/advancedsearch.php")!
    components.queryItems = [
        URLQueryItem(name: "q", value: query),
        URLQueryItem(name: "rows", value: "0"),
        URLQueryItem(name: "output", value: "json")
    ]
    guard let url = components.url else {
        print("ERROR: could not build URL for \(collection.id)")
        exit(1)
    }
    let task = URLSession.shared.dataTask(with: url) { data, response, error in
        defer { semaphore.signal() }
        if let error {
            print("ERROR: request failed for \(collection.id): \(error.localizedDescription)")
            exit(1)
        }
        guard let data else {
            print("ERROR: no data for \(collection.id)")
            exit(1)
        }
        do {
            if let json = try JSONSerialization.jsonObject(with: data) as? [String: Any],
               let response = json["response"] as? [String: Any],
               let numFound = response["numFound"] as? Int {
                counts[collection.id] = numFound
            } else {
                print("ERROR: could not parse response for \(collection.id)")
                exit(1)
            }
        } catch {
            print("ERROR: JSON decode failed for \(collection.id): \(error)")
            exit(1)
        }
    }
    task.resume()
    semaphore.wait()
}

let sortedKeys = counts.keys.sorted()
var output = """
// Generated by `swift run collection-counts` — do not edit by hand.
// Approximate archive.org numFound per featured collection for the default
// English language selection, captured at generation time.
public enum CollectionBundledCounts {
    public static let languages: Set<String> = ["eng"]
    public static let counts: [String: Int] = [
"""

for (i, key) in sortedKeys.enumerated() {
    let comma = i < sortedKeys.count - 1 ? "," : ""
    output += """
\n        "\(key)": \(counts[key]!)\(comma)
"""
}

output += """
\n    ]
}
"""

let fileURL = URL(fileURLWithPath: outputPath)
try output.write(to: fileURL, atomically: true, encoding: .utf8)
print("Wrote \(sortedKeys.count) collection counts to \(outputPath)")
