import Foundation
import VoxglassCore

// Re-scans every item in `collection:librivoxaudio` and regenerates
// `LibriVoxLanguageCounts.swift`. Exits non-zero, without writing, when an item
// carries a `language` value that no `LibriVoxLanguage` entry claims — add the
// value to the right entry's `tokens` (or a new entry), then run this again.
//
//     swift run librivox-languages

let outputPath = "Voxglass/Core/Catalog/LibriVoxLanguageCounts.swift"

struct ScrapePage: Decodable {
    struct Item: Decodable {
        let language: Language?
    }
    enum Language: Decodable {
        case one(String)
        case many([String])
        init(from decoder: Decoder) throws {
            let container = try decoder.singleValueContainer()
            if let value = try? container.decode(String.self) { self = .one(value) } else { self = .many(try container.decode([String].self)) }
        }
        var values: [String] {
            switch self {
            case .one(let value): return [value]
            case .many(let values): return values
            }
        }
    }
    let items: [Item]
    let cursor: String?
}

func fetch(cursor: String?) -> ScrapePage {
    var components = URLComponents(string: "https://archive.org/services/search/v1/scrape")!
    components.queryItems = [
        URLQueryItem(name: "q", value: "collection:librivoxaudio"),
        URLQueryItem(name: "fields", value: "language"),
        URLQueryItem(name: "count", value: "10000")
    ] + (cursor.map { [URLQueryItem(name: "cursor", value: $0)] } ?? [])
    let semaphore = DispatchSemaphore(value: 0)
    nonisolated(unsafe) var result: Result<ScrapePage, Error>?
    URLSession.shared.dataTask(with: components.url!) { data, _, error in
        defer { semaphore.signal() }
        if let error { result = .failure(error); return }
        result = Result { try JSONDecoder().decode(ScrapePage.self, from: data ?? Data()) }
    }.resume()
    semaphore.wait()
    switch result! {
    case .success(let page): return page
    case .failure(let error):
        print("ERROR: scrape request failed: \(error.localizedDescription)")
        exit(1)
    }
}

var counts: [String: Int] = [:]
var unmapped: [String: Int] = [:]
var itemTotal = 0
var cursor: String?
repeat {
    let page = fetch(cursor: cursor)
    for item in page.items {
        itemTotal += 1
        let values = (item.language?.values ?? [])
            .flatMap { $0.split(separator: ";") }
            .map { $0.trimmingCharacters(in: .whitespacesAndNewlines) }
            .filter { !$0.isEmpty }
        if values.isEmpty {
            counts[LibriVoxLanguage.unspecifiedID, default: 0] += 1
            continue
        }
        var ids: Set<String> = []
        for value in values {
            if let language = LibriVoxLanguage.language(forToken: value) {
                ids.insert(language.id)
            } else {
                unmapped[value, default: 0] += 1
            }
        }
        for id in ids { counts[id, default: 0] += 1 }
    }
    cursor = page.cursor
} while cursor != nil

guard unmapped.isEmpty else {
    print("ERROR: archive.org language values with no LibriVoxLanguage entry:")
    for (value, count) in unmapped.sorted(by: { $0.value > $1.value }) {
        print("  \(value): \(count) item(s)")
    }
    exit(1)
}

let date = ISO8601DateFormatter.string(from: Date(), timeZone: .gmt, formatOptions: [.withFullDate])
var lines: [String] = []
lines.append("// Generated by `swift run librivox-languages` — do not edit by hand.")
lines.append("// LibriVox items per `LibriVoxLanguage.id`, \(itemTotal) items scanned on \(date).")
lines.append("// An item tagged with several languages counts once for each.")
lines.append("public enum LibriVoxLanguageCounts {")
lines.append("    public static let generatedOn = \"\(date)\"")
lines.append("    public static let counts: [String: Int] = [")
for language in LibriVoxLanguage.all {
    lines.append("        \"\(language.id)\": \(counts[language.id] ?? 0),")
}
lines.append("    ]")
lines.append("}")
try! (lines.joined(separator: "\n") + "\n").write(toFile: outputPath, atomically: true, encoding: .utf8)
print("Wrote \(outputPath): \(itemTotal) items, \(counts.count) languages with books")
