import AVFoundation
import Foundation
import VoxglassCore

/// Plays the bundled CarPlay confirmation earcons (spec §18.3 rule 6). The
/// tones are committed WAVs in `Voxglass/Resources/CarPlayCues` (generated by
/// `scripts/generate_carplay_cues.py`) — deliberately not speech synthesis,
/// which CI gate G-1 forbids.
@MainActor
public final class BundledCarPlayCuePlayer: CarPlayCuePlaying {
    private var players: [CarPlayCueKind: AVAudioPlayer] = [:]

    public init() {}

    public func play(_ cue: CarPlayCueKind) {
        if players[cue] == nil {
            guard let url = Bundle.main.url(
                forResource: cue.rawValue,
                withExtension: "wav",
                subdirectory: "CarPlayCues"
            ) else { return }
            players[cue] = try? AVAudioPlayer(contentsOf: url)
        }
        players[cue]?.play()
    }
}
